export const TOUR_SELECT = {
  id: true,
  publicId: true,
  title: true,
  shortDescription: true,
  fullDescriptionBlocks: true,
  price: true,
  image: true,
  categories: true,
  tags: true,
  dateFrom: true,
  dateTo: true,
  durationDays: true,
  durationNights: true,
  available: true,
  createdAt: true,
  updatedAt: true,
};
